### ISSUE TITLE
GUI cannot save settings

### ISSUE THREAD

**Issue by AChangAZha** [machinewrapped/gpt-subtrans#27] opened 2023-05-26 16:49 UTC
Version 0.2.1  
When I click the `OK` button, the settings cannot be saved.  
![Snipaste_2023-05-27_00-46-55](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/58546001-9fbf-4e13-be0e-6d6877e10132)

![Snipaste_2023-05-27_00-26-17](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/bc051ee9-ffe0-4ac5-a0ec-d5da02e95eee)

**Comment by machinewrapped** [comment] 2023-05-26 17:01
Thanks for the report, I already have a fix for this, it will be in the next version.

**Comment by machinewrapped** [comment] 2023-05-26 17:20
OK, v0.2.2 is available - can you confirm that the issue is fixed and close it when you have chance?

Thanks!

**Comment by AChangAZha** [comment] 2023-05-26 17:44
Thank you so much! I was just about to report another question to you. Didn't expect you to release a new version so soon and it works!

### Just in case, I still report to you:
When I fill in the options as shown in the picture below, there will be errors when translating. If I don't fill in these options, the program will crash when translating.
![Snipaste_2023-05-27_01-30-57](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/4a3b2878-aff3-454d-95ce-72d089576908)
![Snipaste_2023-05-27_01-13-21](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/283d238a-aa47-4ee4-9be2-5005f72bd177)

### But version 0.2.2 still seems to have this problem:
All batches of subtitles have been translated, but the translated files cannot be saved, and the contents of the project files seem to have been cleared.
![Snipaste_2023-05-27_01-35-54](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/d909bd48-7515-4bf4-8bb2-0fc0db836465)
![Snipaste_2023-05-27_01-40-17](https://github.com/machinewrapped/gpt-subtrans/assets/80208659/8629d265-b35e-4d9a-94ea-799a57b05a7f)

Hope you can fix it soon, thanks again!

**Comment by AChangAZha** [comment] 2023-05-26 17:47
Should I open a new issue?

**Comment by machinewrapped** [comment] 2023-05-26 21:07
Yes please, that's going to take some investigating! 

Do the input subtitles have timestamps? It looks like it's having trouble sorting the translations.

**Closed** 2023-05-27 01:25 UTC
