### ISSUE TITLE
Crash at AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit

### ISSUE THREAD

**Issue by romanr** [machinewrapped/gpt-subtrans#75] opened 2023-10-15 23:23 UTC
- Open GUI.
- open settings dialog. 
- click Save

```
2023-10-16 10:20:27.221 Python[79554:5933254] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000189bfc8c0 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001896f5eb4 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000189b72f20 -[__NSCFString hasSuffix:] + 0
	3   libqcocoa.dylib                     0x0000000110fa811c _ZN20QCocoaSystemTrayIcon13emitActivatedEv + 269824
```

**Comment by machinewrapped** [comment] 2023-10-20 18:03
Thanks, I can't imagine why the CapsLockLED is involved in the settings dialog! I've added some error handling to try to identify the root cause of the error, it will be in the next release.

**Closed** 2023-11-27 18:54 UTC
