### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Jespertnh** [machinewrapped/gpt-subtrans#11] opened 2023-04-20 16:09 UTC
This is probably a really dumb question, but I get this error:

```
python3 gpt-subtrans.py "sub_files/Futurama - S08E02 - 2-D Blacktop.srt" --target_language Dutch --moviename Futurama
Traceback (most recent call last):
  File "gpt-subtrans.py", line 5, in <module>
    from PySubtitleGPT.Helpers import ParseCharacters, ParseSubstitutions
  File "/root/fileBrowserFiles/gpt-subtrans/PySubtitleGPT/Helpers.py", line 14, in <module>
    def UpdateFields(item : dict, update: dict, fields : list[str]):
TypeError: 'type' object is not subscriptable
```

I've used the install bash script to set everything up.
Am I doing something wrong?

**Comment by machinewrapped** [comment] 2023-04-20 19:47
Hi, it's almost certainly something I've done wrong, I'll take a look!

**Comment by machinewrapped** [comment] 2023-04-20 20:14
It seems to be working OK from a clean install on Windows, I'll try it on the mac over the weekend to see if it's an issue with the 'nix install script. Have you tried the GUI?

I'm going to push an update now with a type check in the `UpdateFields` function, which won't fix anything but might at least indicate what the problem is. I've also set the default log level for the command line version to "INFO", so that it's not quite as tight-lipped about what it's doing.

**Comment by Jespertnh** [comment] 2023-04-20 21:02
```
python3 gpt-subtrans.py "sub_files/Futurama - S08E02 - 2-D Blacktop.srt" --target_language Dutch --moviename Futurama
Traceback (most recent call last):
  File "gpt-subtrans.py", line 5, in <module>
    from PySubtitleGPT.Helpers import ParseCharacters, ParseSubstitutions
  File "/root/fileBrowserFiles/gpt-subtrans/PySubtitleGPT/Helpers.py", line 14, in <module>
    def UpdateFields(item : dict, update: dict, fields : list[str]):
TypeError: 'type' object is not subscriptable
```

```
git status
On branch main
Your branch is up to date with 'origin/main'.
```

**Comment by Jespertnh** [comment] 2023-04-20 21:47
Quickly installed xfce4 & a vnc server. This also happens when trying to run the GUI.
![firefox_6k9QnZeoMM](https://user-images.githubusercontent.com/5727163/233494646-4b9c212d-a18c-490f-9ee4-a0da5576159e.png)

**Comment by nekosaur** [comment] 2023-04-21 18:35
Which version of python? I think I got this when I used < 3.10

**Comment by machinewrapped** [comment] 2023-04-22 20:43
I am interested to hear if it is a Python version issue. It's an odd error, I can't really see how there could be a type there instead of a value, but I suppose it could happen if there's been an API change.

**Closed** 2023-05-06 16:35 UTC
