### ISSUE TITLE
Two scenes sometimes get merged into one and the downstream translation become shifted

### ISSUE THREAD

**Issue by anilbey** [machinewrapped/gpt-subtrans#6] opened 2023-04-15 16:58 UTC
Hello, this issue is a bit hard to explain. Please bear with me :) I was trying to translate an English srt file to Turkish. During the process, block 12 and block 13 get merged. 

As a result, 
block **14** of the input became block **13** of the output
block **25** of the input became block **24** of the output
...
block **n** of the input became block **n-1** of the output

This shift causes issues since the timing gets shifted as well.
E.g. block 14's text was supposed to start at `00:00:57,250`, the translated text however becomes block 13 and starts at `00:00:54,333 `.

Here is an example that demonstrates the issue.

Input:
```
12
00:00:51,833 --> 00:00:54,207
and the correct sequence
of its editing

13
00:00:54,333 --> 00:00:57,124
established by means
of this Argentinian material.
```

Output:
```
12
00:00:51,833 --> 00:00:54,207
ve düzenlemenin doğru sırası
bu Arjantin malzemesi aracılığıyla belirlendi.
```

**Comment by anilbey** [comment] 2023-04-15 16:59
The program gave these warnings.
```
WARNING: Unable to match 1 subtitles with a source line
WARNING: Failed to translate 1 subtitles:
```

**Comment by machinewrapped** [comment] 2023-04-15 19:24
Sadly that is something ChatGPT does sometimes, despite explicitly being told not to.  It would probably improve the translation if it updated the timings too, but it does not - as you've observed. I suspect GPT-4 will be less prone to the problem, when it's available for general use.

If the ALLOW_RETRANSLATIONS environment var is true (which it should be by default) the translator will send a reply pointing out the error and asking ChatGPT to try again, which is usually enough for it to correct the mistake. If it fails again it moves on though.

The only other mitigation is to reduce the maximum batch size / reduce the batch threshold (see readme) as each batch is a sync point. It will slow the translation down though (and increase the cost).

I'm planning to integrate the GUI branch into main tomorrow, which has quite a lot of improvements, and at the very least makes it easy to request a retranslation if there's a problem (I still need to add something to highlight batches that had errors reported).

**Comment by machinewrapped** [comment] 2023-04-16 10:42
I realised that you need to set an extra environment variable to request retranslation if the line counts don't match. Add this to your .env file:

ENFORCE_LINE_PARITY=True

I think I'll make that the default, it definitely helps.

**Comment by nekosaur** [comment] 2023-05-14 15:11
I've been experimenting with a node version of subtrans, mainly because I'm not very well versed in python, and I've been using the following initial instructions:

```
Your task is to accurately translate subtitles into a target language. The user will provide lines from a scene in the following format:

<t id="1">
Dialogue to be translated
</t>

You should respond with one matching line in the target language for each original line, in the following format:

<t id="1">
Translated dialogue
</t>

It is important that you do not merge multiple lines into a single line, as this can lead to inaccuracies.

Your translations should be concise and accurate, while still sounding natural; do not improvise.
```

I don't know if it's the use of ids, or the slight rewording of the text, but so far I haven't had a single instance of ChatGPT merging lines. This is of course still quite anecdotal since I've only tested a handful of different subtitles.

**Comment by machinewrapped** [comment] 2023-05-14 15:46
Thanks - this is still by far the biggest issue with the program, I would love to solve it. The annoying thing is that the merged lines usually do read better, but it screws up the timing of subsequent lines - if I could find a better way to match the translations to original lines the merging could be considered a bonus!

I did actually use IDs rather than times originally and it definitely did merge lines, sometime catastrophically, but that was before I hit on the xml-like format, which seems to keep it a bit more focused. I'll try the format you suggest. I've read lately that giving it more than one example of correct output helps too.

I'd be interested in seeing the Node version - I've never used Node, but I dislike Python with a passion so I've considered trying to convert it a few times :-)

**Comment by machinewrapped** [comment] 2023-05-17 21:08
I'm trying a new prompting strategy on this branch:
https://github.com/machinewrapped/gpt-subtrans/tree/prompt-experiments

It's looking promising, I tried it on some subtitles that it messed up badly previously, and so far it has kept them all separate and correct. I'll merge it into main in and push a new version in a couple of days if testing continues to go well.

**Comment by machinewrapped** [comment] 2023-05-19 16:48
After retranslating two movies with zero merged lines I'm pretty confident the issue is fixed!

You can see where it _wants_ to merge lines in one of them though, when individual sentences are broken up and translating them individually wouldn't be grammatically correct. It ends up kind of repeating itself and generating lines that are too long for the timing. 

The ideal solution has to be allowing it to merge lines but clearly indicate which lines have been merged so they can be resynced. This iteration's results are easier to fix up in Subtitle Edit than desyncs though, so it's definitely an improvement, I'll deploy it over the weekend!

**Comment by machinewrapped** [comment] 2023-05-21 11:31
Version 0.2.1 is now released, it has the new prompting strategy and more explicit instructions. It hasn't completely solved the problem, but it does seem to be significantly better.

I will keep working towards improved, error-free translations, but can you try the new version and let me know if you think this issue can (finally) be closed?

**Comment by nekosaur** [comment] 2023-05-21 15:26
Nice! I'll have to try it with the ones I had issues with.

By the way, I created a repo for my node version here https://github.com/nekosaur/gpt-subtrans-node

**Comment by machinewrapped** [comment] 2023-06-11 14:39
I've translated a bunch of subtitles lately with no desyncs occurring, so I'm going to close this issue as fixed!

**Closed by machinewrapped** 2023-06-11 14:39 UTC
